import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-100 text-gray-900 min-h-screen flex flex-col`}
      >
        {/* Header */}
        <header className="bg-white shadow-md p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <a href="/" className="text-2xl font-bold text-indigo-600">
              send.reel
            </a>
            <ul className="flex space-x-4">
              <li>
                <a
                  href="/"
                  className="text-gray-700 hover:text-indigo-600 font-medium"
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/create"
                  className="text-gray-700 hover:text-indigo-600 font-medium"
                >
                  Create Video
                </a>
              </li>
              {/* Add more navigation links as needed */}
            </ul>
          </nav>
        </header>

        {/* Main Content */}
        <main className="flex-grow container mx-auto p-4 md:p-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white p-4 mt-8">
          <div className="container mx-auto text-center text-sm">
            &copy; {new Date().getFullYear()} reel.farm. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
